package Models;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.1.2
 * 2025-06-23T12:15:42.534+01:00
 * Generated source version: 4.1.2
 *
 */
@WebService(targetNamespace = "urn:schemas-attijariwafa-com:transaction-data:TransactionProcessor", name = "ITransactionProcessor")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ITransactionProcessor {

    @WebMethod(action = "reservation")
    @WebResult(name = "reservationResp", targetNamespace = "urn:schemas-attijariwafa-com:transaction-data", partName = "result")
    public ReservationResp reservation(

        @WebParam(partName = "input", name = "reservationReq", targetNamespace = "urn:schemas-attijariwafa-com:transaction-data")
        ReservationReq input
    );

    @WebMethod(action = "fundsTransferValidate")
    @WebResult(name = "fundsTransferValidateResp", targetNamespace = "urn:schemas-attijariwafa-com:transaction-data", partName = "result")
    public FundsTransferValidateResp fundsTransferValidate(

        @WebParam(partName = "input", name = "fundsTransferValidateReq", targetNamespace = "urn:schemas-attijariwafa-com:transaction-data")
        FundsTransferValidateReq input
    );

    @WebMethod(action = "fundsTransferCancel")
    @WebResult(name = "fundsTransferCancelResp", targetNamespace = "urn:schemas-attijariwafa-com:transaction-data", partName = "result")
    public FundsTransferCancelResp fundsTransferCancel(

        @WebParam(partName = "input", name = "fundsTransferCancelReq", targetNamespace = "urn:schemas-attijariwafa-com:transaction-data")
        FundsTransferCancelReq input
    );

    @WebMethod(action = "accountStatement")
    @WebResult(name = "accountStatementResp", targetNamespace = "urn:schemas-attijariwafa-com:transaction-data", partName = "result")
    public AccountStatementResp accountStatement(

        @WebParam(partName = "input", name = "accountStatementReq", targetNamespace = "urn:schemas-attijariwafa-com:transaction-data")
        AccountStatementReq input
    );

    @WebMethod(action = "accountBalance")
    @WebResult(name = "accountBalanceResp", targetNamespace = "urn:schemas-attijariwafa-com:transaction-data", partName = "result")
    public AccountBalanceResp accountBalance(

        @WebParam(partName = "input", name = "accountBalanceReq", targetNamespace = "urn:schemas-attijariwafa-com:transaction-data")
        AccountBalanceReq input
    );

    @WebMethod(action = "operationUpdate")
    @WebResult(name = "operationUpdateResp", targetNamespace = "urn:schemas-attijariwafa-com:transaction-data", partName = "result")
    public OperationUpdateResp operationUpdate(

        @WebParam(partName = "input", name = "operationUpdateReq", targetNamespace = "urn:schemas-attijariwafa-com:transaction-data")
        OperationUpdateReq input
    );

    @WebMethod(action = "queryCustomerAccount")
    @WebResult(name = "queryCustomerAccountResp", targetNamespace = "urn:schemas-attijariwafa-com:transaction-data", partName = "result")
    public QueryCustomerAccountResp queryCustomerAccount(

        @WebParam(partName = "input", name = "queryCustomerAccountReq", targetNamespace = "urn:schemas-attijariwafa-com:transaction-data")
        QueryCustomerAccountReq input
    );

    @WebMethod(action = "accountStatus")
    @WebResult(name = "accountStatusResp", targetNamespace = "urn:schemas-attijariwafa-com:transaction-data", partName = "result")
    public AccountStatusResp accountStatus(

        @WebParam(partName = "input", name = "accountStatusReq", targetNamespace = "urn:schemas-attijariwafa-com:transaction-data")
        AccountStatusReq input
    );

    @WebMethod(action = "operationAdvice")
    @WebResult(name = "operationAdviceResp", targetNamespace = "urn:schemas-attijariwafa-com:transaction-data", partName = "result")
    public OperationAdviceResp operationAdvice(

        @WebParam(partName = "input", name = "operationAdviceReq", targetNamespace = "urn:schemas-attijariwafa-com:transaction-data")
        OperationAdviceReq input
    );

    @WebMethod(action = "operationCancel")
    @WebResult(name = "operationCancelResp", targetNamespace = "urn:schemas-attijariwafa-com:transaction-data", partName = "result")
    public OperationCancelResp operationCancel(

        @WebParam(partName = "input", name = "operationCancelReq", targetNamespace = "urn:schemas-attijariwafa-com:transaction-data")
        OperationCancelReq input
    );

    @WebMethod(action = "customerInfo")
    @WebResult(name = "customerInfoResp", targetNamespace = "urn:schemas-attijariwafa-com:transaction-data", partName = "result")
    public CustomerInfoResp customerInfo(

        @WebParam(partName = "input", name = "customerInfoReq", targetNamespace = "urn:schemas-attijariwafa-com:transaction-data")
        CustomerInfoReq input
    );

    @WebMethod(action = "accountOpening")
    @WebResult(name = "accountOpeningResp", targetNamespace = "urn:schemas-attijariwafa-com:transaction-data", partName = "result")
    public AccountOpeningResp accountOpening(

        @WebParam(partName = "input", name = "accountOpeningReq", targetNamespace = "urn:schemas-attijariwafa-com:transaction-data")
        AccountOpeningReq input
    );

    @WebMethod(action = "operationExec")
    @WebResult(name = "operationExecResp", targetNamespace = "urn:schemas-attijariwafa-com:transaction-data", partName = "result")
    public OperationExecResp operationExec(

        @WebParam(partName = "input", name = "operationExecReq", targetNamespace = "urn:schemas-attijariwafa-com:transaction-data")
        OperationExecReq input
    );

    @WebMethod(action = "customerSummary")
    @WebResult(name = "customerSummaryResp", targetNamespace = "urn:schemas-attijariwafa-com:transaction-data", partName = "result")
    public CustomerSummaryResp customerSummary(

        @WebParam(partName = "input", name = "customerSummaryReq", targetNamespace = "urn:schemas-attijariwafa-com:transaction-data")
        CustomerSummaryReq input
    );

    @WebMethod(action = "accountEvent")
    @WebResult(name = "accountEventResp", targetNamespace = "urn:schemas-attijariwafa-com:transaction-data", partName = "result")
    public AccountEventResp accountEvent(

        @WebParam(partName = "input", name = "accountEventReq", targetNamespace = "urn:schemas-attijariwafa-com:transaction-data")
        AccountEventReq input
    );

    @WebMethod(action = "transactionExec")
    @WebResult(name = "transactionExecResp", targetNamespace = "urn:schemas-attijariwafa-com:transaction-data", partName = "result")
    public TransactionExecResp transactionExec(

        @WebParam(partName = "input", name = "transactionExecReq", targetNamespace = "urn:schemas-attijariwafa-com:transaction-data")
        TransactionExecReq input
    );

    @WebMethod(action = "fundsTransferExecute")
    @WebResult(name = "fundsTransferExecuteResp", targetNamespace = "urn:schemas-attijariwafa-com:transaction-data", partName = "result")
    public FundsTransferExecuteResp fundsTransferExecute(

        @WebParam(partName = "input", name = "fundsTransferExecuteReq", targetNamespace = "urn:schemas-attijariwafa-com:transaction-data")
        FundsTransferExecuteReq input
    );

    @WebMethod(action = "customerAccounts")
    @WebResult(name = "customerAccountsResp", targetNamespace = "urn:schemas-attijariwafa-com:transaction-data", partName = "result")
    public CustomerAccountsResp customerAccounts(

        @WebParam(partName = "input", name = "customerAccountsReq", targetNamespace = "urn:schemas-attijariwafa-com:transaction-data")
        CustomerAccountsReq input
    );
}
