package Models;

import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * Attijariwafa Position Web Services
 *
 * This class was generated by Apache CXF 4.1.2
 * 2025-06-23T12:15:42.582+01:00
 * Generated source version: 4.1.2
 *
 */
@WebServiceClient(name = "TransactionProcessor",
                  wsdlLocation = "file:src/main/resources/wsdl/AttijariwafaTransaction.wsdl",
                  targetNamespace = "urn:schemas-attijariwafa-com:transaction-data:TransactionProcessor")
public class TransactionProcessor extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("urn:schemas-attijariwafa-com:transaction-data:TransactionProcessor", "TransactionProcessor");
    public static final QName PortXML = new QName("urn:schemas-attijariwafa-com:transaction-data:TransactionProcessor", "portXML");
    static {
        URL url = null;
        try {
            url = URI.create("file:src/main/resources/wsdl/AttijariwafaTransaction.wsdl").toURL();
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TransactionProcessor.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:src/main/resources/wsdl/AttijariwafaTransaction.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TransactionProcessor(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TransactionProcessor(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TransactionProcessor() {
        super(WSDL_LOCATION, SERVICE);
    }

    public TransactionProcessor(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public TransactionProcessor(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public TransactionProcessor(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ITransactionProcessor
     */
    @WebEndpoint(name = "portXML")
    public ITransactionProcessor getPortXML() {
        return super.getPort(PortXML, ITransactionProcessor.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ITransactionProcessor
     */
    @WebEndpoint(name = "portXML")
    public ITransactionProcessor getPortXML(WebServiceFeature... features) {
        return super.getPort(PortXML, ITransactionProcessor.class, features);
    }

}
